network = "goerli"
client_release_channel = "demo_env"
client_release_version = "v2.0.0"
services_version = "test"
ethereum_amount_required = 2e16
# Special networking for Demoenvs
routing_mode = "pfs"
matrix_server = "https://transport.demo001.env.raiden.network"
pathfinding_service_address = "https://pfs.demo001.env.raiden.network"

[service_token]
ticker = "SVT"
amount_required = 6e18
swap_amount = 10e18
mintable = true

[transfer_token]
ticker = "WIZ"
amount_required = 2e18
swap_amount = 2e18
mintable = true
