network = "goerli"
client_release_channel = "testing"
client_release_version = "v1.1.0"
services_version = "test"
ethereum_amount_required = 2e16

[service_token]
ticker = "SVT"
amount_required = 6e18
swap_amount = 10e18
mintable = true

[transfer_token]
ticker = "WIZ"
amount_required = 2e18
swap_amount = 2e18
mintable = true