network = "goerli"
client_release_channel = "testing"
client_release_version = "v0.200.0-rc1"
services_version = "dev"

ethereum_amount_required = 2e16

[service_token]
sticker = "LDN"
amount_required = 6e18

[transfer_token]
sticker = "WIZ"
amount_required = 2e18