network = "mainnet"
client_release_channel = "testing"
client_release_version = "v0.200.0-rc8"
services_version = "test"
ethereum_amount_required = 2e16
routing_mode = "local"
cmc_api_key = "30eeec47-754b-4fd1-85c5-a35edf88ff5b"

[service_token]
ticker = "RDN"
amount_required = 6e18

[transfer_token]
ticker = "DAI"
amount_required = 2e18
