network = "mainnet"
client_release_channel = "mainnet"
client_release_version = "v1.0.0"
services_version = "mainnet"
ethereum_amount_required = 125e15
ethereum_amount_required_after_swap = 75e14
routing_mode = "local"

[service_token]
ticker = "RDN"
amount_required = 6e18
swap_amount_1 = 10e18
swap_amount_2 = 20e18
swap_amount_3 = 50e18

[transfer_token]
ticker = "DAI"
amount_required = 2e18
swap_amount_1 = 3e18
swap_amount_2 = 5e18
swap_amount_3 = 10e18
